### ISSUE TITLE
General suggestion

### ISSUE THREAD

**Issue by mt-sette** [kwossi/cli-memory-game#1]
The advantage of using classes is that, data and methods for manipulation data is all in one place. It saves you the trouble of creating functions on the global scope. 

Now that you have an idea of what the app is going to do, maybe you can sketch on a piece of paper which classes you want to create, and each methods and properties they would have. Check UML Class Diagram.

**Comment by kwossi** [comment]
I see what you mean. I changed it now, so that all the game play happens inside the game object. I would be happy about more feedback-

**Comment by mt-sette** [comment]
Looks much better now. More organized. :+1:

**Comment by ZakariaHn** [comment]
You’ve done a great job organizing the code into logical blocks which really helps in understanding the flow of the game.

I have a little observation that you might like to take into consideration. In the class `Board`, I noticed that you manually typed out each row to display the game board, instead, you can use a loop or some iteration method like `forEach` to achieve that (Assuming 'rows' is an array of arrays, where each sub-array represents a row of Tiles). This not only makes your code cleaner and easier to read but also allows for easier modifications to the board size in the future.

Keep up the great work! With a few tweaks and a bit more polishing, your game could be even more engaging.

**Comment by kwossi** [comment]
Thank you for your feedback, Zakaria! I actually updated the showBoard function so that it uses a loop now :) but then forgot to reply to your comment here.

**Comment by ZakariaHn** [comment]
No worries! Most important that it worked :)
