### ISSUE TITLE
The `class Game` have a lot of responsibilities

### ISSUE THREAD

**Issue by mt-sette** [kwossi/cli-memory-game#2]
Some of of the methods handle by the the ´class Game´ could be distributed amount the other classes. 

- the Board class could be responsible for creating a new board.(shuffle tiles, getting a new row, etc).
- The player creation could be a [static method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)  

The constructor could look like this: 

```js
class Game {
    constructor() {
        this.player1 = Player.createPlayer('Player 1');
        this.player2 = Player.createPlayer('Player 2');
        this.board = new Board(/* tiles array here */);
        this.turnCount = 0;
        this.currentPlayer = this.updateCurrentPlayer();
    }
    // ...other methods...
}

```

**Comment by kwossi** [comment]
Thanks for the feedback, I implemented your suggested changed now :)

**Comment by mt-sette** [comment]
Like playing the game. Good mechanics. 

I think you over used the static method, just a bit. :slightly_smiling_face: 

The static method is meant to be used outside of the class without invoking the new keyword. example (Math.PI, Obeject.keys(obj)).  

In case you have a helper method, that is meant to be used internally within the class; this is called a private method. There are ways to prevent this from being accessed outside of the class. But don't worry too much now.

**Comment by kwossi** [comment]
Aaaah, okay. I thought you could make them static whenever you dont necessarily need the method to be a part of the object. So that there is less 'baggage' in the instances of the object. But i can change that back again. ;) 
Thank you for checking!
